create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text not null check (char_length(email) between 3 and 160),
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

comment on table public.leads is
  'Contact form leads submitted through the BAYBIMAI server API.';
