export type DailyLang = "zh" | "en";

export type DailyLesson = {
  id: number;
  week: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  category: string;
  title: string;
  article: string[];
  translationZh: string[];
  takeawayEn: string;
  phrase: string;
  phraseZh: string;
  sayIt: string;
  promptZh: string;
  promptEn: string;
};

export const dailyLessons: DailyLesson[] = [
  {
    id: 1,
    week: 1,
    category: "POSITIONING",
    title: "Say what the company does",
    article: [
      "A founder should be able to explain the company before the listener loses attention. Start with the customer, the problem, and the result. Avoid a long history of how the idea began. A clear sentence gives the other person something concrete to question, remember, and repeat.",
      "Clarity is not the same as making the company sound small. You can describe an ambitious future after people understand the first useful product. The first sentence opens the door; the vision tells them how far the company may travel.",
    ],
    translationZh: [
      "创始人必须在听众失去注意力前讲清公司做什么。先说客户、问题和结果，不要先讲漫长的创业起源。清楚的一句话，才会让对方有东西可以追问、记住并转述。",
      "讲清楚并不等于把公司说小。先让别人理解第一个有用的产品，再谈雄心勃勃的未来。第一句话负责开门，愿景负责告诉别人公司能走多远。",
    ],
    takeawayEn: "Lead with the customer, problem, and result. Earn the right to explain the larger vision next.",
    phrase: "In one sentence, we help…",
    phraseZh: "用一句话说：我们帮助……",
    sayIt: "In one sentence, we help AEC professionals turn BIM knowledge into work-ready capability.",
    promptZh: "不用“平台、赋能、生态”，用两句话介绍你的公司。",
    promptEn: "Describe your company in two sentences without using platform, empower, or ecosystem.",
  },
  {
    id: 2,
    week: 1,
    category: "PROBLEM",
    title: "Make the pain specific",
    article: [
      "Weak pitches describe a large industry problem. Strong pitches describe a painful moment for a particular person. Instead of saying that construction is inefficient, explain what happens when a BIM manager receives an inconsistent model two days before a coordination deadline.",
      "Specific pain creates urgency. It also tells an investor or customer that you have observed the work closely. If the problem can be measured in hours, rework, risk, or lost revenue, include that consequence.",
    ],
    translationZh: [
      "弱的介绍只会描述一个巨大的行业问题；强的介绍会描述某个具体人物的痛苦时刻。不要只说施工行业效率低，而要讲清BIM经理在协调截止前两天收到不一致模型时会发生什么。",
      "具体的痛点会产生紧迫感，也证明你真正观察过工作流程。如果问题可以用时间、返工、风险或损失收入衡量，就把后果说出来。",
    ],
    takeawayEn: "A measurable moment of pain is more persuasive than a broad complaint about an industry.",
    phrase: "The costly moment happens when…",
    phraseZh: "最昂贵的问题发生在……",
    sayIt: "The costly moment happens when teams discover coordination errors just before delivery.",
    promptZh: "描述客户最焦虑的一个具体时刻，以及它造成的后果。",
    promptEn: "Describe one anxious customer moment and the consequence it creates.",
  },
  {
    id: 3,
    week: 1,
    category: "CUSTOMER",
    title: "Choose the first customer",
    article: [
      "A startup can eventually serve many people, but it needs a first customer who feels the problem strongly enough to act now. A narrow starting point improves the product, message, and sales process. It does not permanently limit the company.",
      "Ask who has the problem, who owns the budget, and who can approve a purchase. These may be three different people. A founder who understands that buying group can design a much shorter path to revenue.",
    ],
    translationZh: [
      "创业公司以后可以服务很多人，但最初必须找到一类痛感足够强、愿意现在采取行动的客户。聚焦起点会改善产品、表达和销售流程，并不会永久限制公司。",
      "要弄清谁遇到问题、谁掌握预算、谁能批准采购。这三者可能不是同一个人。理解采购群体，才能设计更短的收入路径。",
    ],
    takeawayEn: "Narrow the first customer and map the user, budget owner, and decision-maker separately.",
    phrase: "Our first ideal customer is…",
    phraseZh: "我们的第一类理想客户是……",
    sayIt: "Our first ideal customer is a small AEC team that needs job-ready BIM training without building a curriculum internally.",
    promptZh: "写出使用者、预算负责人和最终决策者。",
    promptEn: "Name the user, budget owner, and final decision-maker.",
  },
  {
    id: 4,
    week: 1,
    category: "WHY NOW",
    title: "Explain why now",
    article: [
      "A good idea may still be too early or too late. Investors ask why this company should exist now. The answer usually comes from a change in technology, regulation, behavior, cost, or distribution. The change should make a previously difficult solution newly possible or necessary.",
      "Do not simply say that AI is growing. Explain what became cheaper, faster, or more reliable, and how that shift changes customer behavior. A strong why-now argument connects an external change to a practical opening.",
    ],
    translationZh: [
      "好想法也可能出现得太早或太晚。投资人会问为什么这家公司必须现在出现。答案通常来自技术、法规、行为、成本或分发方式的变化。",
      "不要只说AI正在增长。要说明什么变得更便宜、更快或更可靠，以及这种变化如何改变客户行为。好的“为什么是现在”会把外部变化与实际机会连接起来。",
    ],
    takeawayEn: "Connect one external change to a newly possible or newly urgent customer solution.",
    phrase: "This became possible because…",
    phraseZh: "这件事现在成为可能，是因为……",
    sayIt: "This became possible because AI can now assist repeatable review work while experts retain final judgment.",
    promptZh: "指出一个最近发生的变化，以及它为公司创造的机会。",
    promptEn: "Name one recent change and the opening it creates for the company.",
  },
  {
    id: 5,
    week: 1,
    category: "TRACTION",
    title: "Turn activity into evidence",
    article: [
      "Downloads, meetings, and website visits are activity. Retention, repeated use, paid contracts, and referrals are evidence. Founders should know the difference. An impressive number is useful only when it shows that customers receive value and return for more.",
      "When sharing traction, provide a time period and a comparison. Saying that weekly active users grew from twenty to thirty-five in one month is more informative than saying engagement is strong. Honest precision builds trust.",
    ],
    translationZh: [
      "下载量、会议数和网站访问只是活动；留存、重复使用、付费合同和推荐才是证据。数字只有在证明客户得到价值并愿意回来时才真正有用。",
      "分享增长时要给出时间范围和对比。说周活用户一个月内从20增长到35，比笼统地说互动很好更有信息量。诚实而精确会建立信任。",
    ],
    takeawayEn: "Report behavior that proves value, with a time period and an honest comparison.",
    phrase: "The strongest signal we see is…",
    phraseZh: "我们看到的最强信号是……",
    sayIt: "The strongest signal we see is that customers return and ask for the next workflow.",
    promptZh: "把一个虚荣指标改写成能证明客户价值的指标。",
    promptEn: "Replace one vanity metric with a metric that demonstrates customer value.",
  },
  {
    id: 6,
    week: 1,
    category: "STORY",
    title: "Tell one customer story",
    article: [
      "A customer story makes an abstract product visible. Begin with the situation before the product, describe the moment of change, and end with a measurable result. Keep the customer at the center; the company is the guide, not the hero.",
      "One detailed story often teaches more than five feature slides. It shows the buyer, workflow, objection, and outcome in a form people can remember. Protect confidential information and use approved details only.",
    ],
    translationZh: [
      "客户故事能让抽象产品变得可见。先讲使用产品之前的情况，再描述变化发生的时刻，最后以可衡量结果结束。客户是主角，公司只是向导。",
      "一个具体故事往往比五页功能介绍更有效，因为它同时展示了买家、流程、顾虑和结果。注意保护机密，只使用获得许可的细节。",
    ],
    takeawayEn: "Structure the story as before, change, and measurable result—with the customer as hero.",
    phrase: "Before working with us…",
    phraseZh: "在与我们合作之前……",
    sayIt: "Before working with us, the team had no consistent way to prepare junior staff for project delivery.",
    promptZh: "用“之前—变化—结果”写三句话。",
    promptEn: "Write three sentences using before, change, and result.",
  },
  {
    id: 7,
    week: 1,
    category: "REVIEW",
    title: "Make the message repeatable",
    article: [
      "A message is clear when another person can repeat it accurately. After explaining the company, ask what they would tell a colleague. Their answer reveals which parts survived and which parts created confusion.",
      "Do not defend every word of the original pitch. Listen for the language people naturally remember. A repeatable message becomes useful in introductions, internal approvals, and investor partner meetings where you are not in the room.",
    ],
    translationZh: [
      "当别人能够准确复述时，信息才算真正清楚。介绍公司后，可以问对方会怎样向同事转述。答案会暴露哪些内容被记住，哪些造成了困惑。",
      "不要为原来的每个词辩护。观察人们自然记住的语言。可复述的信息才能在引荐、内部审批和你不在场的投资人合伙人会议里传播。",
    ],
    takeawayEn: "Test clarity by asking someone else to repeat the company story in their own words.",
    phrase: "How would you describe this to a colleague?",
    phraseZh: "你会怎么把这件事介绍给同事？",
    sayIt: "How would you describe BAYBIMAI to someone on your project team?",
    promptZh: "请一位朋友复述你的公司；记录他用了哪些词。",
    promptEn: "Ask a friend to repeat your company story and record the words they use.",
  },
  {
    id: 8,
    week: 2,
    category: "DISCOVERY",
    title: "Enter a sales call with a hypothesis",
    article: [
      "A discovery call is not a product presentation. Enter with a hypothesis about the customer’s problem, then ask questions that may prove you wrong. Good discovery uncovers the current workflow, the cost of the problem, previous attempts, and the reason change matters now.",
      "If you speak for most of the call, you are probably collecting too little evidence. The customer’s exact words can improve the product and later become the clearest sales language.",
    ],
    translationZh: [
      "需求访谈不是产品演示。带着对客户问题的假设进入，但要提出可能证明自己错误的问题。好的访谈会发现当前流程、问题成本、过去尝试和现在必须改变的原因。",
      "如果大部分时间都是你在说，很可能收集到的证据太少。客户的原话既能改善产品，也可能成为最清楚的销售语言。",
    ],
    takeawayEn: "Use discovery to test a hypothesis, not to confirm everything you already believe.",
    phrase: "Walk me through how you handle…",
    phraseZh: "请带我了解一下你们现在怎样处理……",
    sayIt: "Walk me through how your team currently reviews a BIM model before delivery.",
    promptZh: "写出三个不能用“是/否”回答的客户问题。",
    promptEn: "Write three customer questions that cannot be answered with yes or no.",
  },
  {
    id: 9,
    week: 2,
    category: "LISTENING",
    title: "Follow the energy",
    article: [
      "Customers reveal priorities through energy. They become more detailed, emotional, or specific when a subject matters. Instead of rushing to the next prepared question, stay with that moment. Ask for a recent example and what happened afterward.",
      "Silence is useful. A short pause gives the customer room to remember and explain. Founders often weaken discovery by answering their own questions too quickly. Curiosity produces better sales information than performance.",
    ],
    translationZh: [
      "客户会通过语气和投入程度暴露优先级。谈到重要问题时，他们会变得更具体、更有情绪。不要急着进入下一个准备好的问题，而要追问最近一次发生的例子及后果。",
      "沉默很有用。短暂停顿会给客户回忆和解释的空间。好奇心通常比表现欲带来更好的销售信息。",
    ],
    takeawayEn: "When a customer becomes specific or emotional, pause and ask for the story behind it.",
    phrase: "Can you give me a recent example?",
    phraseZh: "能给我一个最近发生的例子吗？",
    sayIt: "Can you give me a recent example of a model issue that reached the field?",
    promptZh: "下一次谈话中，至少使用一次追问和三秒停顿。",
    promptEn: "Use one follow-up question and a three-second pause in your next conversation.",
  },
  {
    id: 10,
    week: 2,
    category: "VALUE",
    title: "Sell the outcome, not the feature",
    article: [
      "Features describe what the product contains. Outcomes describe what changes for the customer. Buyers rarely purchase a dashboard because they want another dashboard. They purchase faster decisions, fewer mistakes, lower risk, or more revenue.",
      "Connect each important feature to a workflow and business consequence. If the connection is weak, the feature may not belong in the pitch. The clearest value proposition finishes the sentence: this matters because…",
    ],
    translationZh: [
      "功能说明产品有什么，结果说明客户会发生什么变化。买家很少因为想多看一个仪表盘而购买，他们购买的是更快决策、更少错误、更低风险或更多收入。",
      "把每个重要功能连接到工作流程和商业后果。如果连接很弱，它可能不应该出现在销售介绍里。",
    ],
    takeawayEn: "Translate every feature into a changed workflow and a business consequence.",
    phrase: "This matters because…",
    phraseZh: "这很重要，因为……",
    sayIt: "The audit is independent. This matters because project teams often normalize their own recurring errors.",
    promptZh: "选择一个功能，写出它改变的流程和商业结果。",
    promptEn: "Choose one feature and state the workflow and business outcome it changes.",
  },
  {
    id: 11,
    week: 2,
    category: "OBJECTIONS",
    title: "Treat objections as information",
    article: [
      "An objection is not always rejection. It may reveal missing trust, unclear value, bad timing, or an unaddressed stakeholder. First acknowledge the concern, then ask what is behind it. Do not answer before you understand the real objection.",
      "A useful response has three parts: confirm the concern, provide relevant evidence, and agree on the next step. Defensive answers may win an argument and lose the customer.",
    ],
    translationZh: [
      "异议不一定等于拒绝，它可能暴露信任不足、价值不清、时机不对或遗漏了某个利益相关者。先承认顾虑，再询问背后的原因，不要在理解真正异议前急着回答。",
      "有效回应包含三步：确认顾虑、提供相关证据、约定下一步。防御性的回答可能赢得争论却失去客户。",
    ],
    takeawayEn: "Understand the concern before answering it; then respond with evidence and a next step.",
    phrase: "That makes sense. What is the main concern behind it?",
    phraseZh: "这很合理。背后最主要的顾虑是什么？",
    sayIt: "That makes sense. Is the main concern budget, timing, or confidence in the result?",
    promptZh: "写下客户最可能提出的异议，并准备一个追问。",
    promptEn: "Write the most likely customer objection and one question to understand it.",
  },
  {
    id: 12,
    week: 2,
    category: "PRICING",
    title: "Discuss price without apologizing",
    article: [
      "Price is part of the product. State it clearly, explain what is included, and stop talking. Founders often weaken a fair price by apologizing or offering a discount before the buyer reacts.",
      "If the customer hesitates, return to scope and value. Ask which assumption does not work: budget, timing, expected outcome, or internal approval. A discount should exchange for something meaningful, such as reduced scope, faster payment, or a longer commitment.",
    ],
    translationZh: [
      "价格是产品的一部分。清楚说明价格和包含内容，然后停下来。创始人经常在买家还没有反应前就道歉或主动打折，从而削弱合理价格。",
      "如果客户犹豫，回到范围和价值，确认是哪项假设不成立。折扣应换取有意义的条件，例如缩小范围、更快付款或更长期承诺。",
    ],
    takeawayEn: "State price calmly. If there is resistance, diagnose the assumption before changing the number.",
    phrase: "The price for this scope is…",
    phraseZh: "这项服务范围的价格是……",
    sayIt: "The price for this scope is five thousand dollars, including the audit, findings review, and final report.",
    promptZh: "大声说出你的价格、包含内容，然后停顿三秒。",
    promptEn: "Say your price and scope aloud, then remain silent for three seconds.",
  },
  {
    id: 13,
    week: 2,
    category: "DEMO",
    title: "Demo the change",
    article: [
      "A strong demo follows a customer story. Begin with a recognizable problem, show the shortest path to a meaningful result, and explain why that result matters. Avoid touring every menu and setting.",
      "Prepare for failure. Use realistic data, test the critical path, and keep a short recorded backup. The best demo feels like the customer is watching their own future workflow rather than observing someone else’s software.",
    ],
    translationZh: [
      "好的演示遵循客户故事：从熟悉的问题开始，展示通向有意义结果的最短路径，再解释结果为什么重要。不要逐个游览所有菜单和设置。",
      "要为失败准备备用方案。使用真实感数据、测试关键路径并保留短录屏。最好的演示让客户像是在观看自己未来的工作流程。",
    ],
    takeawayEn: "Show one customer problem becoming one meaningful result through the shortest credible path.",
    phrase: "Let me show you the shortest path from…to…",
    phraseZh: "我来展示从……到……的最短路径。",
    sayIt: "Let me show you the shortest path from an unchecked model to a prioritized audit report.",
    promptZh: "把你的Demo压缩为“问题—操作—结果”三步。",
    promptEn: "Reduce your demo to three beats: problem, action, result.",
  },
  {
    id: 14,
    week: 2,
    category: "FOLLOW-UP",
    title: "Make the next step easy",
    article: [
      "A good meeting can disappear without a specific next step. Before ending, confirm who will do what and by when. Send a short follow-up that reflects the customer’s priorities rather than repeating your entire pitch.",
      "Useful follow-ups contain context, one important insight, the agreed action, and a date. Make replying easy. Momentum is often lost not because interest disappeared, but because responsibility remained vague.",
    ],
    translationZh: [
      "没有具体下一步，再好的会议也会消失。结束前确认谁在什么时候做什么。跟进邮件应反映客户重点，而不是重复完整销售介绍。",
      "有效跟进包含背景、一个重要洞察、已约定行动和日期。让回复变得容易。很多机会失去不是因为兴趣消失，而是责任没有说清。",
    ],
    takeawayEn: "End every useful conversation with an owner, an action, and a date.",
    phrase: "To keep momentum, the next step is…",
    phraseZh: "为了保持进展，下一步是……",
    sayIt: "To keep momentum, I’ll send the pilot outline today and you’ll confirm the project team by Friday.",
    promptZh: "写一封不超过五句话的会后跟进。",
    promptEn: "Write a post-meeting follow-up in no more than five sentences.",
  },
  {
    id: 15,
    week: 3,
    category: "FUNDRAISING",
    title: "Know why you are raising",
    article: [
      "Fundraising is not a measure of personal worth. It is a financing decision. A founder should know why outside capital is necessary, what milestone it will purchase, and why that milestone increases the company’s value.",
      "If customer revenue can fund the next stage without slowing a critical opportunity, bootstrapping may preserve flexibility. If speed, research, or market timing requires more resources now, investment may be appropriate. The answer depends on the business, not the fashion.",
    ],
    translationZh: [
      "融资不是衡量个人价值的方式，而是一项融资决策。创始人需要知道为什么必须使用外部资本、资金将购买哪个里程碑，以及这个里程碑为什么会提高公司价值。",
      "如果客户收入能够支持下一阶段且不会错过关键机会，自筹可能保留更多灵活性；如果速度、研发或市场时机需要立即投入更多资源，融资可能更合适。",
    ],
    takeawayEn: "Raise to purchase a defined milestone, not to receive social validation.",
    phrase: "This round is designed to unlock…",
    phraseZh: "这轮融资是为了实现……",
    sayIt: "This round is designed to unlock repeatable customer acquisition and twelve months of product development.",
    promptZh: "用一句话说明融资将购买什么关键里程碑。",
    promptEn: "State in one sentence which milestone the round will purchase.",
  },
  {
    id: 16,
    week: 3,
    category: "ROUND SIZE",
    title: "Connect capital to a plan",
    article: [
      "A fundraising target should come from a plan, not from a round label. Estimate the people, infrastructure, sales work, and legal costs required to reach the next fundable milestone. Add a reasonable buffer and understand the dilution created by the financing instrument.",
      "Investors may challenge the assumptions. That is useful. A founder who can explain how each major expense changes the probability of success appears disciplined rather than merely ambitious.",
    ],
    translationZh: [
      "融资目标应来自计划，而不是来自“种子轮”这类标签。估算达到下一个可融资里程碑所需的人力、基础设施、销售和法律成本，加入合理缓冲，并理解融资工具造成的稀释。",
      "投资人可能质疑这些假设，这是有价值的。能够解释每项主要支出如何提高成功概率，会让创始人显得有纪律，而不只是有野心。",
    ],
    takeawayEn: "Build the raise from milestone costs, runway, buffer, and expected dilution.",
    phrase: "The capital will be allocated to…",
    phraseZh: "资金将主要用于……",
    sayIt: "The capital will be allocated to product reliability, design partners, and a focused go-to-market motion.",
    promptZh: "列出融资后的三项最大支出及其对应结果。",
    promptEn: "List the three largest uses of capital and the result expected from each.",
  },
  {
    id: 17,
    week: 3,
    category: "MARKET",
    title: "Build the market from reality",
    article: [
      "A large market slide is not enough. Investors need to see a believable path from the first customer to a much larger opportunity. Begin with the narrow segment you can reach, estimate its spending, and explain the adjacent segments that become available as the product improves.",
      "Top-down research can provide context, but bottom-up assumptions show how the business might actually grow. State the assumptions so another person can challenge or improve them.",
    ],
    translationZh: [
      "一张巨大市场规模幻灯片还不够。投资人需要看到从第一类客户走向更大机会的可信路径。先从真正可触达的细分市场和支出开始，再说明产品成熟后可以进入哪些相邻市场。",
      "自上而下研究提供背景，自下而上的假设才展示业务如何增长。把假设写出来，别人才能质疑或改进。",
    ],
    takeawayEn: "Show a bottom-up path from a reachable beachhead to credible adjacent markets.",
    phrase: "We start with…, then expand into…",
    phraseZh: "我们从……开始，然后扩展到……",
    sayIt: "We start with BIM training for small AEC teams, then expand into audit workflows and enterprise knowledge systems.",
    promptZh: "写出起始市场和两个相邻市场，以及扩展条件。",
    promptEn: "Name the beachhead and two adjacent markets, including what unlocks each expansion.",
  },
  {
    id: 18,
    week: 3,
    category: "MOAT",
    title: "Describe what compounds",
    article: [
      "A feature can be copied. A durable advantage usually compounds through data, distribution, workflow integration, trust, community, or operating speed. The company should become harder to replace as it serves more customers and learns more.",
      "Avoid claiming that technology is proprietary without explaining why it matters. Describe the mechanism: what improves, why competitors cannot obtain it quickly, and how customers experience the difference.",
    ],
    translationZh: [
      "功能可以被复制。持久优势通常来自数据、分发、工作流整合、信任、社区或运营速度的持续积累。公司服务越多客户、学习越多，就应该越难被替代。",
      "不要只声称技术是专有的。要说明什么会改善、竞争者为什么不能快速获得，以及客户如何感受到差异。",
    ],
    takeawayEn: "A moat is a compounding mechanism, not an adjective attached to the technology.",
    phrase: "Our advantage compounds as…",
    phraseZh: "我们的优势会随着……而累积。",
    sayIt: "Our advantage compounds as every audit improves the rules and examples used in future reviews.",
    promptZh: "完成句子：客户越多，我们的____就越好，因为____。",
    promptEn: "Complete: As we serve more customers, our ___ improves because ___.",
  },
  {
    id: 19,
    week: 3,
    category: "METRICS",
    title: "Choose the metric that reveals value",
    article: [
      "The best early metric represents the value customers receive. For a collaboration product, it might be active teams completing a shared workflow. For a learning product, it might be learners finishing a job-relevant task and returning the next week.",
      "A single metric cannot explain the whole company, but it focuses decisions. Pair it with guardrails so growth does not hide poor quality, high cost, or customer dissatisfaction.",
    ],
    translationZh: [
      "最好的早期指标代表客户真正得到的价值。协作产品可能关注完成共同流程的活跃团队；学习产品可能关注完成工作相关任务并在下一周返回的学习者。",
      "单一指标不能解释整个公司，但能帮助集中决策。同时需要质量、成本和满意度等护栏指标，避免增长掩盖问题。",
    ],
    takeawayEn: "Select one value metric and pair it with quality and cost guardrails.",
    phrase: "The metric that best reflects customer value is…",
    phraseZh: "最能反映客户价值的指标是……",
    sayIt: "The metric that best reflects customer value is the number of teams completing a verified workflow each week.",
    promptZh: "选择一个核心价值指标和两个护栏指标。",
    promptEn: "Choose one core value metric and two guardrail metrics.",
  },
  {
    id: 20,
    week: 3,
    category: "INVESTOR FIT",
    title: "Qualify investors too",
    article: [
      "Fundraising is mutual selection. A recognizable fund name does not guarantee a useful partnership. Learn the investor’s stage, check size, decision process, reserves, relevant experience, and behavior when companies struggle.",
      "Speak with founders the investor has backed, including one company that performed well and one that did not. The quality of an investor becomes most visible when plans change, not when the announcement is published.",
    ],
    translationZh: [
      "融资是双向选择。知名基金不一定等于适合的合作伙伴。要了解投资阶段、支票规模、决策流程、后续储备、相关经验，以及公司困难时的行为。",
      "与被投创始人交流，既包括发展顺利的，也包括不顺利的。投资人真正的质量通常在计划改变时体现，而不是在融资新闻发布时。",
    ],
    takeawayEn: "Reference-check investors for fit, process, and behavior during difficult periods.",
    phrase: "How do you support founders when the original plan changes?",
    phraseZh: "当原计划发生变化时，你们如何支持创始人？",
    sayIt: "How do you typically work with a company between the seed round and the next major milestone?",
    promptZh: "为潜在投资人准备三个反向尽调问题。",
    promptEn: "Prepare three reverse-diligence questions for a potential investor.",
  },
  {
    id: 21,
    week: 3,
    category: "UPDATES",
    title: "Write an investor update people can scan",
    article: [
      "A useful investor update is brief, factual, and regular. Lead with the important change, show a small set of metrics, name the current challenge, and make one or two specific requests. Consistency builds confidence even when every month is not positive.",
      "Avoid hiding bad news inside long paragraphs. Explain what happened, what you learned, and what action you are taking. Good investors can help only when they understand the real situation.",
    ],
    translationZh: [
      "有效的投资人更新应该简短、真实且规律。先写最重要变化，展示少量指标，说明当前挑战，再提出一两个具体请求。即使不是每个月都顺利，持续更新也会建立信任。",
      "不要把坏消息藏在长段落里。说明发生了什么、学到了什么、正在采取什么行动。投资人只有了解真实情况才能帮助。",
    ],
    takeawayEn: "Use a repeatable structure: change, metrics, challenge, learning, and specific asks.",
    phrase: "The most important change this month is…",
    phraseZh: "本月最重要的变化是……",
    sayIt: "The most important change this month is that three design partners moved from testing to weekly use.",
    promptZh: "用五个项目符号写一封本月投资人更新。",
    promptEn: "Draft this month’s investor update in five bullets.",
  },
  {
    id: 22,
    week: 4,
    category: "NETWORKING",
    title: "Open with relevance",
    article: [
      "Networking becomes easier when the opening is relevant to the other person. Mention a specific idea from their work, then connect it to a question you genuinely care about. This is more natural than delivering a complete pitch without invitation.",
      "Your goal is not to extract value from every conversation. Look for useful exchanges, shared problems, and reasons to continue. A strong network grows from repeated trust, not from collecting contact details.",
    ],
    translationZh: [
      "当开场与对方真正相关时，社交会容易很多。提到对方工作中的一个具体观点，再连接到你真正在意的问题，比未经邀请就完整推销自然得多。",
      "目标不是从每次谈话中立刻提取价值，而是寻找有用交流、共同问题和继续联系的理由。强大的人脉来自重复建立的信任，不是联系人数量。",
    ],
    takeawayEn: "Begin with a specific point of relevance and a genuine question, not an unsolicited pitch.",
    phrase: "Your point about…made me think about…",
    phraseZh: "你关于……的观点让我想到……",
    sayIt: "Your point about judgment and pruning made me think about quality control in BIM workflows.",
    promptZh: "为下一场Meetup中的一个人准备具体开场。",
    promptEn: "Prepare one specific opening for a person at your next meetup.",
  },
  {
    id: 23,
    week: 4,
    category: "ASKING",
    title: "Make a small, precise ask",
    article: [
      "People can respond to a precise request. They struggle with broad requests such as ‘help me with my startup.’ Ask for one piece of feedback, a twenty-minute conversation, or an introduction to a particular type of person.",
      "Explain why the request fits them and make declining easy. Respectful specificity protects the relationship and increases the chance of a useful response.",
    ],
    translationZh: [
      "人们容易回应明确请求，却很难回应“帮帮我的创业公司”这种宽泛要求。可以只请求一条反馈、一次20分钟交流，或介绍某一类具体人物。",
      "说明这个请求为什么适合对方，并让拒绝变得容易。尊重且具体的表达既保护关系，也提高获得有效回应的概率。",
    ],
    takeawayEn: "Ask for one bounded action, explain the fit, and leave room for an easy no.",
    phrase: "Would you be open to…",
    phraseZh: "你是否愿意……",
    sayIt: "Would you be open to a twenty-minute call to pressure-test our first customer segment?",
    promptZh: "把一个宽泛请求改写为20分钟内可以完成的请求。",
    promptEn: "Rewrite a broad request as something that can be completed in twenty minutes.",
  },
  {
    id: 24,
    week: 4,
    category: "NEGOTIATION",
    title: "Separate positions from interests",
    article: [
      "A position is what someone says they want. An interest is the reason underneath it. A customer may request a lower price because the budget is fixed, because approval feels risky, or because the scope is unclear. Each interest suggests a different solution.",
      "Ask questions before making concessions. Better agreements often come from changing scope, timing, payment structure, or risk—not simply splitting the difference.",
    ],
    translationZh: [
      "立场是对方声称想要什么，利益是它背后的原因。客户要求降价，可能因为预算固定、审批风险高或范围不清；每种原因需要不同解决方案。",
      "让步前先提问。更好的协议往往来自调整范围、时间、付款结构或风险，而不是简单各退一步。",
    ],
    takeawayEn: "Diagnose the underlying interest before changing price or accepting a stated position.",
    phrase: "Help me understand what is driving that request.",
    phraseZh: "请帮我理解是什么原因推动了这个要求。",
    sayIt: "Help me understand what is driving the request for a shorter pilot.",
    promptZh: "为客户的一个立场写出三种可能的深层原因。",
    promptEn: "Write three possible interests behind one customer position.",
  },
  {
    id: 25,
    week: 4,
    category: "HIRING",
    title: "Hire for the next constraint",
    article: [
      "An impressive resume is not a hiring plan. Early teams should hire against the company’s next important constraint. Define the outcome the person must produce, the decisions they will own, and the evidence that shows they can work in an uncertain environment.",
      "Do not copy a large company job description. Startups need clarity about responsibility and flexibility about method. The first conversation should make both the opportunity and the difficulty visible.",
    ],
    translationZh: [
      "耀眼履历不等于招聘计划。早期团队应针对公司的下一个关键瓶颈招聘，明确这个人必须产生的结果、负责的决策，以及能证明他适应不确定环境的证据。",
      "不要照搬大公司职位描述。创业公司需要对责任清楚、对方法灵活。第一次沟通应该同时让机会和困难都可见。",
    ],
    takeawayEn: "Define the next constraint and required outcome before defining the title.",
    phrase: "The outcome this role owns is…",
    phraseZh: "这个职位负责的结果是……",
    sayIt: "The outcome this role owns is turning five design partners into repeatable paid deployments.",
    promptZh: "不用职位名称，描述下一位成员必须交付的结果。",
    promptEn: "Describe the result your next teammate must deliver without naming a job title.",
  },
  {
    id: 26,
    week: 4,
    category: "LEADERSHIP",
    title: "Name the difficult truth",
    article: [
      "Teams lose time when everyone senses a problem but nobody names it. A founder should describe the observable facts, explain the consequence, and invite correction. This creates a shared problem without assigning unnecessary blame.",
      "Direct communication can still be respectful. Separate the person from the behavior or result, and agree on a next action. Avoiding a hard conversation usually makes the eventual conversation harder.",
    ],
    translationZh: [
      "当所有人都感觉到问题却没人说出来时，团队会浪费时间。创始人应描述可观察事实、解释后果并邀请纠正，这样能建立共同问题而不是不必要地指责某人。",
      "直接沟通仍然可以保持尊重。把人和行为或结果分开，并约定下一步。回避困难谈话，通常只会让最终谈话更困难。",
    ],
    takeawayEn: "State observable facts and consequences, invite correction, and agree on the next action.",
    phrase: "The pattern I’m noticing is…",
    phraseZh: "我注意到的模式是……",
    sayIt: "The pattern I’m noticing is that decisions are being reopened after work has already started.",
    promptZh: "用“事实—后果—下一步”写一段困难谈话。",
    promptEn: "Draft a difficult conversation using fact, consequence, and next action.",
  },
  {
    id: 27,
    week: 4,
    category: "CLOSING",
    title: "Close the conversation clearly",
    article: [
      "A conversation should end with clarity even when the answer is no. Summarize what you heard, state whether there is a fit, and confirm the next action. Ambiguous optimism creates more work than an honest decision.",
      "If the timing is wrong, ask what future event would make the conversation relevant again. Record that condition and follow up when it actually occurs, not every two weeks without new information.",
    ],
    translationZh: [
      "即使答案是否定的，谈话也应该清楚结束。总结你听到的内容，说明是否匹配并确认下一步。模糊的乐观比诚实决定制造更多工作。",
      "如果时机不对，询问未来什么事件会让谈话重新变得相关。记录这个条件，并在它真正发生时跟进，而不是没有新信息也每两周追问。",
    ],
    takeawayEn: "Prefer a clear decision or condition for re-engagement over vague, endless follow-up.",
    phrase: "Based on what we discussed, the next step is…",
    phraseZh: "根据我们刚才的讨论，下一步是……",
    sayIt: "Based on what we discussed, there is a fit if the pilot can show weekly use by three teams.",
    promptZh: "为“合适”“暂时不合适”各写一句清晰结尾。",
    promptEn: "Write one clear closing sentence for a fit and one for not yet.",
  },
  {
    id: 28,
    week: 4,
    category: "PITCH",
    title: "Deliver the founder story",
    article: [
      "A founder story connects insight, evidence, and ambition. Explain what you observed that others missed, what you built because of it, what customers have proved, and what becomes possible if the company succeeds. Keep each link concrete.",
      "Confidence does not require pretending that uncertainty is gone. Strong founders know what they believe, what they have proved, and what they still need to learn. End with the future you are inviting the listener to help create.",
    ],
    translationZh: [
      "创始人故事连接洞察、证据和野心。说明你观察到了别人忽略的什么、因此做了什么、客户已经证明了什么，以及公司成功后会带来什么可能。每一环都要具体。",
      "自信不等于假装不确定性已经消失。强大的创始人知道自己相信什么、证明了什么、还需要学习什么。最后描述你邀请听众共同创造的未来。",
    ],
    takeawayEn: "Connect unique insight, built evidence, customer proof, and an ambitious but concrete future.",
    phrase: "What we have learned is…, and that opens the possibility of…",
    phraseZh: "我们已经学到……，而这打开了……的可能性。",
    sayIt: "What we have learned is that expert judgment can become a repeatable workflow, and that opens the possibility of a new operating layer for AEC teams.",
    promptZh: "录制一段60秒介绍：洞察、产品、证据、未来。",
    promptEn: "Record a 60-second pitch covering insight, product, evidence, and future.",
  },
];

export const dailyCopy = {
  zh: {
    skip: "跳到今日晨读",
    eyebrow: "FOUNDER DAILY · 28 DAY SPRINT",
    title: "每天 6 分钟，\n把创业英语变成肌肉记忆。",
    intro:
      "不是背单词，也不是收藏文章。每天读一段、听一遍、说一句、写两句。完成今天，明天才出现下一课。",
    rules: ["英文先行", "中文按需", "一天一课"],
    today: "今日必读",
    day: "第",
    daySuffix: "天",
    week: "第 {week} 周",
    weekNames: [
      "讲清公司",
      "卖出价值",
      "理解融资",
      "领导与连接",
      "读懂市场",
      "诚实谈AI",
      "竞争定位",
      "带队穿越变化",
    ],
    streak: "连续阅读",
    streakUnit: "天",
    completed: "已完成",
    total: "共 56 天",
    listen: "听英文",
    pause: "暂停",
    resume: "继续",
    stop: "停止",
    speed: "语速",
    voice: "朗读声音",
    previewVoice: "试听",
    previewingVoice: "试听中…",
    voiceReady: "声音已选择，可以开始朗读",
    showHelp: "看中文理解",
    hideHelp: "收起中文",
    helpTitle: "中文理解",
    phraseTitle: "今天带走一句",
    speakTitle: "现在说出口",
    writeTitle: "写两句，不求完美",
    saved: "已保存在本机",
    draftPlaceholder: "用英文写下你的回答……",
    complete: "完成今天的 6 分钟",
    doneToday: "今天完成。明天回来继续。",
    roundComplete: "56 天完成。从讲清公司到读懂市场，你已经把创业英语变成了肌肉记忆。",
    speechPlaying: "正在朗读今日英文",
    speechLoading: "正在生成所选声音…",
    speechPaused: "朗读已暂停",
    speechStopped: "朗读已停止",
    speechComplete: "今日朗读完成",
    speechUnsupported: "语音朗读暂不可用",
    speechError: "所选声音暂不可用，请稍后再试",
    routeTitle: "28 天路线",
    routeIntro: "漏读不会跳课；下一次回来仍从未完成的一课继续。",
    localNote: "进度只保存在当前浏览器，不需要登录。",
  },
  en: {
    skip: "Skip to today's reading",
    eyebrow: "FOUNDER DAILY · 28 DAY SPRINT",
    title: "Six minutes a day.\nBuild founder English into muscle memory.",
    intro:
      "No word-list collecting. Read one passage, listen once, say one line, and write two. Finish today; the next lesson arrives tomorrow.",
    rules: ["English first", "Help on demand", "One lesson a day"],
    today: "Today's non-negotiable",
    day: "Day",
    daySuffix: "",
    week: "Week {week}",
    weekNames: [
      "Explain the company",
      "Sell the value",
      "Understand funding",
      "Lead and connect",
      "Reading the Market",
      "Talking About AI Honestly",
      "Positioning Against Competitors",
      "Leading Through Fast Change",
    ],
    streak: "Reading streak",
    streakUnit: "days",
    completed: "Completed",
    total: "56 days total",
    listen: "Listen",
    pause: "Pause",
    resume: "Resume",
    stop: "Stop",
    speed: "Speed",
    voice: "Reading voice",
    previewVoice: "Preview",
    previewingVoice: "Previewing…",
    voiceReady: "Voice selected. Ready to read.",
    showHelp: "Show key takeaway",
    hideHelp: "Hide takeaway",
    helpTitle: "Key takeaway",
    phraseTitle: "Keep this phrase",
    speakTitle: "Say it now",
    writeTitle: "Write two imperfect sentences",
    saved: "Saved on this device",
    draftPlaceholder: "Write your answer in English…",
    complete: "Complete today's six minutes",
    doneToday: "Done for today. Return tomorrow for the next lesson.",
    roundComplete: "All 56 days complete. From explaining the company to reading the market, founder English is now muscle memory.",
    speechPlaying: "Reading today's English aloud",
    speechLoading: "Preparing the selected voice…",
    speechPaused: "Reading paused",
    speechStopped: "Reading stopped",
    speechComplete: "Today's reading is complete",
    speechUnsupported: "Speech is temporarily unavailable",
    speechError: "The selected voice is temporarily unavailable. Please try again.",
    routeTitle: "The 28-day route",
    routeIntro: "Missing a day never skips a lesson. You resume from the next unfinished one.",
    localNote: "Progress stays in this browser. No account required.",
  },
} as const;

export type DailyCopy = (typeof dailyCopy)[DailyLang];
